services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: aparkautepino
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: aparkautepino:1.0
    ports:
      - "127.0.0.1:8090:8090"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aparkautepino
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVER_PORT: 8090
volumes:
  mysql_data:
